package desafio4.views;

import controllers.InventoryCtrl;
import controllers.LoanCtrl;
import helpers.ApplicationContext;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import models.Inventory;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import models.Loan;

public class ReturnFrm extends javax.swing.JPanel {
    private InventoryCtrl controller;
    private LoanCtrl loanController;
    private List<Loan> loans;
    private Loan selectedLoan;
    
    public ReturnFrm() {
        initComponents();
        
        controller = new InventoryCtrl();
        loanController = new LoanCtrl();
        
        initTable();
        
        ApplicationContext.setTitleValue("Prestamos | Libreria");
        
        approveBtn.setEnabled(false);
        finishBtn.setEnabled(false);
    }
    
    private void initTable() {
        loans = loanController.getActiveLoans();
       
        DefaultTableModel tableModel = new DefaultTableModel();
        
        tableModel.addColumn("Id");
        tableModel.addColumn("Estado");
        tableModel.addColumn("Responsable");
        tableModel.addColumn("Administrador");
        tableModel.addColumn("Inicio");
        tableModel.addColumn("Finalización");
        tableModel.addColumn("Mora");
        tableModel.addColumn("Días de retraso");
        
        for (Loan loan : loans) {
            String formattedPrice = (loan.getPrice() != null && !loan.getPrice().isEmpty()) ? "$" + loan.getPrice() : "$0.00";

            tableModel.addRow(new Object[]{
                loan.getLoanId(),
                loan.getLoanStateName(),
                loan.getResponsable(),
                loan.getAdmin(),
                loan.getStartDate(),
                loan.getEndDate(),
                formattedPrice,
                loan.getPendingDays()
            });
        }


        
        returnsTbl.setModel(tableModel);
    }
    
    private void handleTableClick() {
        String state = selectedLoan.getLoanStateName();
        materialsTxt.setText(loanController.getMaterialsFromLoan(selectedLoan.getLoanId()));
        
        if (state.equals("Pendiente de aprobación")) {
            approveBtn.setEnabled(true);
            finishBtn.setEnabled(false);
        } else if(state.equals("Finalizado")) {
            approveBtn.setEnabled(false);
            finishBtn.setEnabled(false);
        } else {
            approveBtn.setEnabled(false);
            finishBtn.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        returnsTbl = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        searchTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        finishBtn = new javax.swing.JButton();
        approveBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        materialsTxt = new javax.swing.JEditorPane();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnsTbl.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        returnsTbl.setForeground(new java.awt.Color(51, 51, 51));
        returnsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        returnsTbl.setFocusable(false);
        returnsTbl.setGridColor(new java.awt.Color(43, 111, 145));
        returnsTbl.setSelectionBackground(new java.awt.Color(43, 111, 145));
        returnsTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnsTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(returnsTbl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 700, -1));

        jPanel3.setBackground(new java.awt.Color(245, 251, 248));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        searchTxt.setForeground(new java.awt.Color(51, 51, 51));
        searchTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 212, 218), 1, true));
        searchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtActionPerformed(evt);
            }
        });
        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchTxtKeyTyped(evt);
            }
        });
        jPanel3.add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 980, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(154, 168, 180));
        jLabel10.setText("Buscar");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1020, 110));

        finishBtn.setBackground(new java.awt.Color(82, 190, 127));
        finishBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        finishBtn.setForeground(new java.awt.Color(255, 255, 255));
        finishBtn.setText("Finalizar");
        finishBtn.setBorder(null);
        finishBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        finishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishBtnActionPerformed(evt);
            }
        });
        jPanel1.add(finishBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 620, 140, 40));

        approveBtn.setBackground(new java.awt.Color(82, 190, 127));
        approveBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        approveBtn.setForeground(new java.awt.Color(255, 255, 255));
        approveBtn.setText("Aprobar");
        approveBtn.setBorder(null);
        approveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        approveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(approveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 620, 140, 40));

        materialsTxt.setEditable(false);
        materialsTxt.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(materialsTxt);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 290, 390));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(154, 168, 180));
        jLabel8.setText("Materiales");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, -1, -1));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void returnsTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnsTblMouseClicked
        int modelRowIndex = returnsTbl.convertRowIndexToModel(returnsTbl.getSelectedRow());

        int id = (Integer) returnsTbl.getModel().getValueAt(modelRowIndex, 0);
            
        for (Loan loan : loans) {
            if (loan.getLoanId() == id) {
                selectedLoan = loan;
                break;
            }
        }
        
        handleTableClick();
            
    }//GEN-LAST:event_returnsTblMouseClicked

    private void searchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtActionPerformed

    }//GEN-LAST:event_searchTxtActionPerformed

    private void searchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtKeyReleased

    private void searchTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyTyped
        DefaultTableModel model = (DefaultTableModel) returnsTbl.getModel();
        TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<DefaultTableModel>(model);

        returnsTbl.setRowSorter(rowSorter);
        rowSorter.setRowFilter(RowFilter.regexFilter(searchTxt.getText()));
    }//GEN-LAST:event_searchTxtKeyTyped

    private void finishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishBtnActionPerformed
        boolean feeWasExecuted = false;
        double finalFee = 0.00;
        double currentFee = 0.00;
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate endDate = LocalDate.parse(selectedLoan.getEndDate(), formatter);

        LocalDate actualDate = LocalDate.now();

        long difference = java.time.temporal.ChronoUnit.DAYS.between(endDate, actualDate);
        
        if (difference > 0) {
            String currentYear = selectedLoan.getEndDate().substring(0, 4);
            
            currentFee = loanController.getCurrentFee(currentYear);
            
            finalFee = currentFee * difference;
            
            boolean ok = loanController.addFeeToLoan(selectedLoan.getLoanId(), finalFee, difference);
            
            if(!ok) return;
            
            feeWasExecuted = true;
        }
        
        boolean ok = loanController.finishLoan(selectedLoan.getLoanId());
        
        if(!ok) return;
        
        if (!feeWasExecuted) {
            JOptionPane.showMessageDialog(null, "Prestamo finalizado exitosamente.");
        } else {
            DecimalFormat df = new DecimalFormat("#.00");
            JOptionPane.showMessageDialog(null, "Prestamo finalizado exitosamente. Se aplico una mora diaria de $"+df.format(currentFee)+" por " + difference + " dias de retraso. ($"+df.format(finalFee)+")");
        }
        
        
        initTable();
    }//GEN-LAST:event_finishBtnActionPerformed

    private void approveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtnActionPerformed
        boolean ok = loanController.approveLoan(selectedLoan.getLoanId());
        
        if(!ok) return;
        
        JOptionPane.showMessageDialog(null, "Prestamo aprobado exitosamente.");
        initTable();
    }//GEN-LAST:event_approveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveBtn;
    private javax.swing.JButton finishBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JEditorPane materialsTxt;
    private javax.swing.JTable returnsTbl;
    private javax.swing.JTextField searchTxt;
    // End of variables declaration//GEN-END:variables
}
