package desafio4.views;

import controllers.UsersCtrl;
import helpers.Validators;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import models.User;
import models.UserType;
import org.apache.commons.codec.digest.DigestUtils;

public class UsersFrm extends javax.swing.JPanel {
    private List<UserType> userTypes;
    private List<User> users;
    private UsersCtrl controller;

    public UsersFrm() {
        initComponents();
        
        Validators.allowNumbers(phoneTxt, 8);
        
        initData();
        initUserTypes();
        initTable();
    }
    
    public void initData() {
        controller = new UsersCtrl();
        userTypes = controller.getUserTypes();
    }
    
    public void initTable() {
        users = controller.getUsers();
        
        DefaultTableModel tableModel = new DefaultTableModel();
        
        tableModel.addColumn("Código");
        tableModel.addColumn("Correo electrónico");
        tableModel.addColumn("Tipo de usuario");
        tableModel.addColumn("Teléfono");
        
        for (int i = 0; i < users.size(); i++) {
            User user = users.get(i);
            tableModel.addRow(new Object[]{user.getIdentificationCode(), user.getEmail(), user.getUserTypeName(), user.getPhone()});
        }
        
        userTbl.setModel(tableModel);
    }
    
    public void initUserTypes() {
        userTypesCb.removeAllItems();
        
        userTypesCb.addItem("Selecciona un tipo de usuario");
        
        for (int i = 0; i < userTypes.size(); i++) {
            userTypesCb.addItem(userTypes.get(i).getUserTypeName());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        passwordTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        codeTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        userTypesCb = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        continueBtn2 = new javax.swing.JButton();
        continueBtn3 = new javax.swing.JButton();
        continueBtn4 = new javax.swing.JButton();
        continueBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTbl = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(245, 251, 248));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordTxt.setBackground(new java.awt.Color(255, 255, 255));
        passwordTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        passwordTxt.setForeground(new java.awt.Color(51, 51, 51));
        passwordTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 212, 218), 1, true));
        passwordTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordTxtKeyReleased(evt);
            }
        });
        jPanel4.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 340, 40));

        emailTxt.setBackground(new java.awt.Color(255, 255, 255));
        emailTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        emailTxt.setForeground(new java.awt.Color(51, 51, 51));
        emailTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 212, 218), 1, true));
        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });
        emailTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailTxtKeyReleased(evt);
            }
        });
        jPanel4.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 340, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(154, 168, 180));
        jLabel2.setText("Contraseña");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(154, 168, 180));
        jLabel3.setText("Correo electrónico");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(154, 168, 180));
        jLabel4.setText("Teléfono");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        phoneTxt.setBackground(new java.awt.Color(255, 255, 255));
        phoneTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        phoneTxt.setForeground(new java.awt.Color(51, 51, 51));
        phoneTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 212, 218), 1, true));
        phoneTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneTxtKeyReleased(evt);
            }
        });
        jPanel4.add(phoneTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 340, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(154, 168, 180));
        jLabel5.setText("Tipo de usuario");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        codeTxt.setBackground(new java.awt.Color(255, 255, 255));
        codeTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        codeTxt.setForeground(new java.awt.Color(51, 51, 51));
        codeTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 212, 218), 1, true));
        codeTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codeTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codeTxtKeyTyped(evt);
            }
        });
        jPanel4.add(codeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 340, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(154, 168, 180));
        jLabel6.setText("Código de identificación");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        userTypesCb.setBackground(new java.awt.Color(255, 255, 255));
        userTypesCb.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        userTypesCb.setForeground(new java.awt.Color(51, 51, 51));
        userTypesCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1" }));
        userTypesCb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 212, 218)));
        jPanel4.add(userTypesCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 340, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 380, 480));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBtn.setBackground(new java.awt.Color(82, 190, 127));
        addBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Agregar");
        addBtn.setBorder(null);
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel2.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 90, 40));

        continueBtn2.setBackground(new java.awt.Color(82, 190, 127));
        continueBtn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        continueBtn2.setForeground(new java.awt.Color(255, 255, 255));
        continueBtn2.setText("Actualizar");
        continueBtn2.setBorder(null);
        continueBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        continueBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(continueBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 90, 40));

        continueBtn3.setBackground(new java.awt.Color(82, 190, 127));
        continueBtn3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        continueBtn3.setForeground(new java.awt.Color(255, 255, 255));
        continueBtn3.setText("Eliminar");
        continueBtn3.setBorder(null);
        continueBtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        continueBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(continueBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 90, 40));

        continueBtn4.setBackground(new java.awt.Color(82, 190, 127));
        continueBtn4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        continueBtn4.setForeground(new java.awt.Color(255, 255, 255));
        continueBtn4.setText("Limpiar");
        continueBtn4.setBorder(null);
        continueBtn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        continueBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(continueBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 90, 40));

        continueBtn.setBackground(new java.awt.Color(82, 190, 127));
        continueBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        continueBtn.setForeground(new java.awt.Color(255, 255, 255));
        continueBtn.setText("Reestablecer contraseña");
        continueBtn.setBorder(null);
        continueBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        continueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBtnActionPerformed(evt);
            }
        });
        jPanel2.add(continueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 190, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 290, 130));

        userTbl.setBackground(new java.awt.Color(255, 255, 255));
        userTbl.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        userTbl.setForeground(new java.awt.Color(51, 51, 51));
        userTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        userTbl.setFocusable(false);
        userTbl.setGridColor(new java.awt.Color(43, 111, 145));
        userTbl.setSelectionBackground(new java.awt.Color(43, 111, 145));
        userTbl.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(userTbl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 620, 600));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void continueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBtnActionPerformed

    }//GEN-LAST:event_continueBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String code = codeTxt.getText().trim();
        String email = emailTxt.getText().trim();
        String phone = phoneTxt.getText().trim();
        Object userType = userTypesCb.getSelectedItem();
        String password = passwordTxt.getText().trim();
        
        if (code.length() == 0 || email.length() == 0 || phone.length() == 0 || userType == "Selecciona un tipo de usuario" || password.length() == 0) {
            JOptionPane.showMessageDialog(null, "No se permiten campos vacios");
            return;
        }
        
        boolean isEmailValid = Validators.matchesRegex(email, Validators.getEmailRegex());
        
        if(!isEmailValid) {
            JOptionPane.showMessageDialog(null, "El correo electrónico ingresado es invalido.");
            return;
        }
        
        String encryptedPassword = DigestUtils.sha1Hex(password);
        
        int userTypeId = -1;
        
        for (int i = 0; i < userTypes.size(); i++) {
            if(userTypes.get(i).getUserTypeName().equals(userType)) {
                userTypeId = userTypes.get(i).getUserTypeId();
                break;
            }
        }
        
        if(userTypeId == -1) {
            JOptionPane.showMessageDialog(null, "No se encontró el tipo de usuario seleccionado.");
            return;
        }
        
        User user = new User();
        
        user.setIdentificationCode(code);
        user.setEmail(email);
        user.setPassword(encryptedPassword);
        user.setPhone(phone);
        user.setHasToResetPassword(false);
        user.setUserTypeId(userTypeId);
        
        boolean isOk = controller.registerUser(user);
        
        if(!isOk) return;
        
        JOptionPane.showMessageDialog(null, "Se creo el usuario correctamente.");
        
        initTable();
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void continueBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continueBtn2ActionPerformed

    private void continueBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continueBtn3ActionPerformed

    private void continueBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continueBtn4ActionPerformed

    private void codeTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeTxtKeyReleased
        String code = codeTxt.getText();
        boolean isOk = Validators.checkTextLength(code, 8);
        
        if(!isOk) {
            codeTxt.setText(code.substring(0, 8));
        }
    }//GEN-LAST:event_codeTxtKeyReleased

    private void codeTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_codeTxtKeyTyped

    private void emailTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTxtKeyReleased
        String email = emailTxt.getText();
        boolean isOk = Validators.checkTextLength(email, 100);
        
        if(!isOk) {
            emailTxt.setText(email.substring(0, 99));
        }
    }//GEN-LAST:event_emailTxtKeyReleased

    private void phoneTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneTxtKeyReleased
        
    }//GEN-LAST:event_phoneTxtKeyReleased

    private void passwordTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTxtKeyReleased
        String password = passwordTxt.getText();
        boolean isOk = Validators.checkTextLength(password, 16);
        
        if(!isOk) {
            passwordTxt.setText(password.substring(0, 16));
        }
    }//GEN-LAST:event_passwordTxtKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField codeTxt;
    private javax.swing.JButton continueBtn;
    private javax.swing.JButton continueBtn2;
    private javax.swing.JButton continueBtn3;
    private javax.swing.JButton continueBtn4;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JTable userTbl;
    private javax.swing.JComboBox<String> userTypesCb;
    // End of variables declaration//GEN-END:variables
}
